#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rgba8) uniform readonly image2D baseImage;
layout(binding = 1, rgba8) uniform readonly image2D seamFixImage;
layout(binding = 2, rgba8) uniform readonly image2D seamFixAlpha;
layout(binding = 3, rgba8) uniform image2D resultImage;

void main(){
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

	vec4 pixel = imageLoad(baseImage, pixelCoords);
	vec4 seamFixPix = imageLoad(seamFixImage, pixelCoords);
	vec4 alpha = imageLoad(seamFixAlpha, pixelCoords);

	alpha.g = alpha.r;
	alpha.b = alpha.r;

	pixel.rgb = pixel.rgb * (1.0 - alpha.rgb) + seamFixPix.rgb * alpha.rgb;
	
	if (pixel.b < 1.0/255.0 && pixel.r < 1.0/255.0 && pixel.g < 1.0/255.0){
		pixel.rgb = vec3(0.0, 0.0, 1.0);
	}

	imageStore(resultImage, pixelCoords, pixel);
}