#version 450

#define PI 3.1415926538
#define HPI 1.5707963267

layout (local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rgba8) uniform readonly image2D referenceOSNorm; // The unmodified os normal map of the mesh
layout(binding = 1, rgba8) uniform readonly image2D baseOSNorm; // The base normal which another normal map will be layered onto
layout(binding = 2, rgba8) uniform readonly image2D layerOSNorm; // The normal which will be layered on top of the base normal
layout(binding = 3, rgba8) uniform image2D resultNorm;

void main(){
	// This function combines two different OS normals by rotating the layer norm by the same rotation that would transform the mesh normals into the base normal

	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	vec3 refNorm = imageLoad(referenceOSNorm, pixelCoords).rgb;
	vec3 baseNorm = imageLoad(baseOSNorm, pixelCoords).rgb;
	vec3 layerNorm = imageLoad(layerOSNorm, pixelCoords).rgb;

	vec4 pixel = vec4(layerNorm, 1.0);

	imageStore(resultNorm, pixelCoords, vec4(layerNorm, 1.0)); // Initially we just copy all of layer norm onto the result image

	if (refNorm == vec3(0.0, 0.0, 0.0)){
		imageStore(resultNorm, pixelCoords, vec4(0.0, 0.0, 0.0, 1.0));
		return;
	}

	refNorm = refNorm * 2.0 - 1.0;
	refNorm /= length(refNorm);
	baseNorm = baseNorm * 2.0 - 1.0;
	baseNorm /= length(baseNorm);
	layerNorm = layerNorm * 2.0 - 1.0;
	layerNorm /= length(layerNorm);

	if (dot(refNorm, baseNorm) == 1.0){
		// If the base and reference vectors are parallel then the result is just the layered vector
		return;
	}

	vec3 b = cross(refNorm, baseNorm); // This vector is orthogonal to both the reference and base normal vectors
	float angle = acos(dot(refNorm, baseNorm)); // The angle between the reference and base normal vectors

	// The components of the layer norm along the vector orthogonal to both reference and base normal vectors
	vec3 layerAlongB = (dot(b, layerNorm) / dot(b, b)) * b;
	vec3 layerPerpB = layerNorm - layerAlongB;

	vec3 w = cross(b, layerPerpB);

	if (length(w) == 0.0 || length(layerPerpB) == 0.0){
		return;
	}

	float x_1 = cos(angle)/length(layerPerpB);
	float x_2 = sin(angle)/length(w);

	if (isinf(x_1) || isinf(x_2)){
		return;
	}

	vec3 rotatedLayerPerpB = length(layerPerpB) * (x_1 * layerPerpB + x_2 * w);

	vec3 rotatedLayer = rotatedLayerPerpB + layerAlongB;

	vec3 mixedNorm = rotatedLayer / length(rotatedLayer);

	mixedNorm *= 0.5;
	mixedNorm += 0.5;

	if (mixedNorm == vec3(0.0) || any(isinf(mixedNorm)) || any(isnan(mixedNorm))){
		return;
	}

	pixel = vec4(mixedNorm, 1.0);

	imageStore(resultNorm, pixelCoords, pixel);
}