#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout(binding = 1, rgba8) uniform readonly image2D baseImage;
layout(binding = 1, rg16f) uniform image2D resultImage;

void main(){
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	ivec2 imageDims = imageSize(baseImage);

	vec2 relativeCoord = vec2(pixelCoords) / vec2(imageDims);
	vec4 resultPixel = vec4(relativeCoord, 1.0, 1.0);

	imageStore(resultImage, pixelCoords, resultPixel);
}