C:/VulkanSDK/1.3.296.0/Bin/glslc.exe shader.vert -o vert.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe shader.frag -o frag.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe Wshader.vert -o Wvert.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe Wshader.frag -o Wfrag.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe UIshader.vert -o UIvert.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe UIshader.frag -o UIfrag.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe UVshader.vert -o UVvert.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe UVshader.frag -o UVfrag.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe BFshader.vert -o BFvert.spv
C:/VulkanSDK/1.3.296.0/Bin/glslc.exe BFshader.frag -o BFfrag.spv