C:/VulkanSDK/1.4.328.1/Bin/glslc.exe Flatshader.vert -o Flatvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe Flatshader.frag -o Flatfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe Wshader.vert -o Wvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe Wshader.frag -o Wfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UIshader.vert -o UIvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UIshader.frag -o UIfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UIGrayshader.vert -o UIGrayvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UIGrayshader.frag -o UIGrayfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UVshader.vert -o UVvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe UVshader.frag -o UVfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe BFshader.vert -o BFvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe BFshader.frag -o BFfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe OS_BFshader.vert -o OS_BFvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe OS_BFshader.frag -o OS_BFfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe TS_BFshader.vert -o TS_BFvert.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe TS_BFshader.frag -o TS_BFfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe AC_BFshader.frag -o AC_BFfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe AC_Flatshader.frag -o AC_Flatfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe AC_OS_BFshader.frag -o AC_OS_BFfrag.spv
C:/VulkanSDK/1.4.328.1/Bin/glslc.exe AC_TS_BFshader.frag -o AC_TS_BFfrag.spv